#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$0")"

cargo run --manifest-path=$SCRIPTS_DIR/Cargo.toml --bin=run_examples

#set -o errexit
#set -o nounset

#readonly DOCKER_UID="${UID:-0}"
#readonly DOCKER_GID="${GID:-0}"
#readonly DOCKER_USER="${USER:-root}"

## Run Oak server.
#"$SCRIPTS_DIR/build_server_docker"
#"$SCRIPTS_DIR/docker_run" --detach ./bazel-bin/oak/server/oak
#readonly SERVER_CONTAINER_ID="$(docker ps --quiet --latest)"

## Run Oak examples.
#find examples -type f -name run -exec "$SCRIPTS_DIR/docker_run" {} \;

#docker stop "$SERVER_CONTAINER_ID"

