name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file=Dockerfile --tag=oak:latest

  check-formatting:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ./scripts/docker_run ./scripts/check_formatting

  build-server:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ./scripts/build_server_docker
