name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: login
      env:
        GOOGLE_CLOUD_CI: ${{ secrets.GOOGLE_CLOUD_CI }}
      run: echo "$GOOGLE_CLOUD_CI" | docker login -u _json_key --password-stdin https://gcr.io
    - name: Pull the Docker image
      run: docker pull gcr.io/oak-ci/oak:latest
    - name: Build the Docker image
      run: docker build . --file=Dockerfile --pull --cache-from=gcr.io/oak-ci/oak:latest --tag=gcr.io/oak-ci/oak:latest
    - name: Push the Docker image
      run: docker push gcr.io/oak-ci/oak:latest

  check-formatting:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ./scripts/docker_run ./scripts/check_formatting

  build-server:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ./scripts/build_server_docker
